# Generated by Django 3.1.4 on 2021-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210608_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofile',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
